### ISSUE TITLE
sxhkdrc grave key

### ISSUE THREAD

**Issue by vimeitor** [Almehdi/dotfiles#1]
Hello,

I casually found your dotfiles when looking for something about sxhkd. Just so you know, the reason the following code doesn't work (line 39 of sxhkdrc) is because the grave key is not the apostrophe key; the grave key is the one under the ESC button (the ` or ~). If it still doesn't do anything, try to rewrite it as 'grave' instead of 'Grave'.

```
## Move window to.. (does not work on my keyboard)
super + Grave # apostrophe
    bspc window -s last
```

Take care,

Adria

**Comment by shellkr** [comment]
It is not a important key for me (never used it). On my Swedish 
keyboard I need to press Alt Gr and apostroph two times 
(super+AltGr+apostroph x 2) so it was better to change it to the Grave 
to make it single click.. I did it during the initial set up and never 
looked back at it since.. Thanks anyway. I hope you found my configs 
interesting. ;)

**Comment by vimeitor** [comment]
Oh, I see :)

Unfortunately, a lot of the software out there is made for US keyboards, so people that have different keyboards do have sometimes trouble.

Your config was actually helpful. Thanks for putting it up here on github!

Take care,

Adria
