### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by pjhalsli** [Almehdi/dotfiles#2]

**Comment by shellkr** [comment]
Hey! Sorry for the late answer... have been abroad on holiday (6 weeks). I
am primarily on the federated network Mastodon as shellkr. I like the fact
that no singular company own my data. I can move to different servers or
host my own instance e.t.c.. I have also tried to find you. So through
there it is a sure way. Maybe I try MeWe eventually but it looks too
commercial (but what is their revenue stream?). They say they don't track
me... but no one would be honest about such stuff. With Mastodon I know..
because they can't. ;)
